[package]
name = "RustyPomodoro"
version = "0.1.0"
edition = "2024"

[dependencies]
directories = "6.0.0"
serde = { version="1.0.219", features=["derive"]}
serde_json = "1.0.143"
crossterm = "0.29.0"
